//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSitesi.Model.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblTestimonial
    {
        public int TestimonialID { get; set; }
        [Required(ErrorMessage ="Bu Alan Boþ Geçilemez")]
        public string NameSurname { get; set; }
        [Required(ErrorMessage = "Bu Alan Boþ Geçilemez")]
        public string ImageUrl { get; set; }
        [Required(ErrorMessage = "Bu Alan Boþ Geçilemez")]
        [MinLength(50,ErrorMessage ="Minumum 50 karakter olmalý")]
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
